//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELSO.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dELSO3AEntities : DbContext
    {
        public dELSO3AEntities()
            : base("name=ELSOContext")
        {
        }
    
        //protected override void OnModelCreating(DbModelBuilder modelBuilder)
        //{
        //    throw new UnintentionalCodeFirstException();
        //}
    
        public virtual DbSet<DailyReccurence> DailyReccurence { get; set; }
        public virtual DbSet<WeeklyReccurence> WeeklyReccurence { get; set; }
        public virtual DbSet<MonthlyReccurence> MonthlyReccurence { get; set; }
        public virtual DbSet<Daily> Daily { get; set; }
        public virtual DbSet<Event> Event { get; set; }
        public virtual DbSet<EventMaxCount> EventMaxCount { get; set; }
        public virtual DbSet<EventType> EventType { get; set; }
        public virtual DbSet<EventWebResource> EventWebResource { get; set; }
        public virtual DbSet<Monthly> Monthly { get; set; }
        public virtual DbSet<Registration> Registration { get; set; }
        public virtual DbSet<Person> Person { get; set; }
        public virtual DbSet<PersonRole> PersonRole { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Attendance> Attendance { get; set; }
        public virtual DbSet<Pattern> Pattern { get; set; }
        public virtual DbSet<Session> Session { get; set; }
        public virtual DbSet<PatternType> PatternType { get; set; }
        public virtual DbSet<SessionWebResource> SessionWebResource { get; set; }
        public virtual DbSet<WebResource> WebResource { get; set; }
        public virtual DbSet<Weekly> Weekly { get; set; }
    }
}
