//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELSO.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("EVNT_WEB_RSRC")]
    public partial class EventWebResource : BaseEntity
    {
        [Key]
        [Column("EVNT_UID", Order = 0)]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public int EventId { get; set; }
        [Key]
        [Column("WEB_RSRC_UID", Order = 1)]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public int WebResourceId { get; set; }
 
    
        public virtual Event Event { get; set; }
        public virtual WebResource WebResource { get; set; }
    }
}
