//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELSO.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("PRERASGNT")]
    public partial class Registration : BaseEntity
    {
        [Key]
        [Column("PRERASGNT_UID")]
        public int Id { get; set; }
        [Column("ASGNE_PRSN_ID")]
        public int PersonId { get; set; }

        [Column("EVNT_UID")]
        public Nullable<int> EventId { get; set; }

        [StringLength(4), Column("PRSN_ROLE_CD")]
        public string RoleCode { get; set; }

        [Column("ASGND_DTM", TypeName = "datetime2")]
        public System.DateTime AssignmentDate { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual Person Person { get; set; }
        public virtual Role Role { get; set; }
    }
}
