//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELSO.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("PRSN")]
    public partial class Person : BaseEntity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Person()
        {
            this.Registrations = new HashSet<Registration>();
            this.PersonRoles = new HashSet<PersonRole>();
            this.Attendances = new HashSet<Attendance>();
            Organization = "SSA";
        }

        [Key]
        [Column("PRSN_UID")]
        public int Id { get; set; }

        [Required]
        [StringLength(62), Column("ORG_NM")]
        public string Organization { get; set; }

        [StringLength(62), Column("FNM")]
        public string FirstName { get; set; }

        [StringLength(62), Column("LNM")]
        public string LastName { get; set; }

        [Required]
        [StringLength(126), Column("EMAILADDR")]
        public string Email { get; set; }

        [StringLength(35), Column("PHNNUM")]
        public string Phone { get; set; }

        [StringLength(6)]
        public string SSA_PIN { get; set; }
 
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Registration> Registrations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonRole> PersonRoles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Attendance> Attendances { get; set; }

    }
}
