//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELSO.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("RCURPATRN_SESN")]
    public partial class Session : BaseEntity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Session()
        {
            this.Attendances = new HashSet<Attendance>();
            this.SessionWebResource = new HashSet<SessionWebResource>();
        }

        [Key]
        [Column("RCURPATRN_SESN_UID")]
        public int SessionId { get; set; }

        [Column("CNCLN_DTM", TypeName = "datetime2")]
        public Nullable<System.DateTime> CancellationDate { get; set; }

        [Column("ORIGL_STDTM", TypeName = "datetime2")]
        public System.DateTime OriginalStartDate { get; set; }

        [Column("RSCHD_DTM", TypeName = "datetime2")]
        public Nullable<System.DateTime> RescheduledDate { get; set; }

        [Column("RCURPATRN_UID")]
        public int PatternId { get; set; }
        [Column("RCURPATRN_CYCL_ID")]
        public int PatternCycleId { get; set; }

        [Column("EFF_STDTM", TypeName = "datetime2")]
        public System.DateTime StartDate { get; set; }

        [Column("EFF_ENDTM", TypeName = "datetime2")]
        public Nullable<System.DateTime> EndDate { get; set; }

        [StringLength(254), Column("LOC_TXT")]
        public string Location { get; set; }

        [StringLength(254), Column("SESN_DESC")]
        public string sessionDescription { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Attendance> Attendances { get; set; }
        public virtual Pattern Pattern { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SessionWebResource> SessionWebResource { get; set; }
    }
}
