//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELSO.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class WebResource : BaseEntity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WebResource()
        {
            this.EventWebResource = new HashSet<EventWebResource>();
            this.SessionWebResource = new HashSet<SessionWebResource>();
        }

        [Key]
        [Column("WEB_RSRC_UID ")]
        public int WebResourceId { get; set; }

        [StringLength(150)]
        [Column("WEB_RSRC_NM")]
        public string WebResourceName { get; set; }

        [Column("WEB_RSRC_DESC")]
        public string WebResourceDescription { get; set; }

        [Column("URL_ADDR")]
        public string URL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventWebResource> EventWebResource { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SessionWebResource> SessionWebResource { get; set; }
    }
}
